# Generated by Django 3.2.11 on 2024-12-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_tb_1_candy_or_cookie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_1',
            options={'verbose_name': '用戶資料庫', 'verbose_name_plural': '用戶資料庫'},
        ),
    ]
