# Generated by Django 3.2.11 on 2024-12-21 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_tb_1_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_1',
            options={'ordering': ['_time'], 'verbose_name': '用戶資料庫', 'verbose_name_plural': '用戶資料庫'},
        ),
        migrations.AddField(
            model_name='tb_1',
            name='_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
