# Generated by Django 3.2.11 on 2024-12-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20241221_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_1',
            options={'verbose_name': '用戶資料庫', 'verbose_name_plural': '用戶資料庫'},
        ),
        migrations.RemoveField(
            model_name='tb_1',
            name='_time',
        ),
    ]
